version: 0.0.1.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

artifacts:
    - path: artifacts/*.*nupkg
      name: Packages

image:
    - Ubuntu1804

install:
    - sh: wget https://dot.net/v1/dotnet-install.sh
    - sh: sudo chmod +x ./dotnet-install.sh
    - sh: sudo ./dotnet-install.sh
    - sh: sudo dotnet tool install fake-cli -g

build_script:
    - sh: fake run ./src/build.fsx
                    