version: 0.0.1.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

artifacts:
    - path: artifacts/*.*nupkg
      name: Packages

image:
    - Ubuntu1804

install:
    - sh: wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    - sh: sudo dpkg -i packages-microsoft-prod.deb
    - sh: sudo add-apt-repository universe
    - sh: sudo apt-get install apt-transport-https
    - sh: sudo apt-get update
    - sh: sudo apt-get install dotnet-sdk-2.2

build_script:
    - sh: fake run ./src/build.fsx
                    