install:
    - cmd: dotnet tool install fake-cli -g

build_script:
    - cmd: fake run ./src/build.fsx

skip_tags: true

image: Visual Studio 2019 Preview

cache:
    - '%LocalAppData%\NuGet\Cache'    
    - '%LocalAppData%\NuGet\v3-cache'
    - '%UserProfile%\.nuget'

nuget:
    project_feed: true

artifacts:
    - path: artifacts/*.nupkg

version: 0.0.2-{branch}{build}

configuration: Debug

environment:
    debugsymbols: true
    optimization: false

branches:
    only:
        - master
        - develop

for:
- 
    branches:
        only:
            - master

    version: 0.0.2

    configuration: Release

    environment:
        debugsymbols: false
        optimization: true
