version: 0.0.1.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

artifacts:
    - path: artifacts/*.*nupkg
      name: Packages

image:
    - Ubuntu1804

install:
    - sh: >-
        wget https://dot.net/v1/dotnet-install.sh
        ./dotnet-install.sh
        dotnet tool install fake-cli -g
    - sh: 

build_script:
    - sh: >-
                    